language: generic
sudo: requried
services:
  - docker

before_install:
  - docker build -t testme -f  Dockerfile.dev .

script:
  - docker run -e CI=true testme npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-599964014638"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    

